### ISSUE TITLE
[Suggestion] Security issue

### ISSUE THREAD

**Issue by Alfreditto** [duiqt/herta_kuru#10]
If you look in the files you can see the address of the update and with a simple python code you can try to saturate the server.
I would recommend that if you receive a lot of requests from the same IP, the server should set a time out of a few seconds.

**Comment by sr229** [comment]
If the source of the statistics server is open, I could probably go ahead and add it in 

![download](https://github.com/duiqt/herta_kuru/assets/14976516/c0d9d274-b75d-4a99-8709-aa3dbcf4a839)

**Comment by risbi0** [comment]
@sr229 The server is made in express js. Here's the [source code](https://github.com/risbi0/kuru-kuru-count-api). I appreciate the help!

**Comment by risbi0** [comment]
Added a rate limiter. This issue should be resolved now.

**Comment by risbi0** [comment]
On second thought, the issue isn't resolved. The global counter is removed and I'll let someone else implement an api with proper request authentication.

**Comment by fred913** [comment]
The counter has paused, awaiting additional remediation measures, as a result of the excessive traffic and malicious flood of requests.

**Comment by sr229** [comment]
Hmm, the counter seems relatively simple, I'll cook something.

**Comment by fred913** [comment]
No, the main branch in the main repository is not ready to be reviewed
currently. If you really wish to contribute to the project please check my
fork of the repository and contribute to the new branch where we are all
working on.

The problem is that the goal counter is currently filled by bad actors'
actions. So we are on our working on the protection rules of the project,
building our own production server.

**Comment by AozoraDev** [comment]
Heyya!
Allow me to introduce myself... uh... it's not important. And I also created a kurukuru website, inspired by this website.

I noticed that the developer is facing unexpected flooding of requests, so I have a little suggestion to address this, well, not exactly... but rather to reduce it.

1. CORS!!!
A rather old-fashioned but still functional approach would be to restrict the API to only accept requests from your own website CMIIW.
Since you're using ExpressJS, you can utilize the "cors" middleware.
2. Leveraging the "isTrusted" property of the Event (which is quite useless in this context).
Well, because, uh... clever individuals could add isTrusted: true to the headers/body. But hey! It can provide a little bit of protection.
3. Rate limit
Because imagine if that bad person were to make requests at a 1 nanosecond interval, it would undoubtedly cause your API to explode under the immense pressure, like that submersible accident (RIP, btw).

I still have many steps to reduce this flood of requests, but I'm currently a bit lazy to write them down.

**Comment by fred913** [comment]
@AozoraDev 
Thanks! But this issue will be held while we're working on the new structure of the project.

**Comment by fred913** [comment]
@AozoraDev They should have the same behavior finally. I mean, bad ones still can spam the counter, while normal users can play with Kuru-kuru.

**Comment by AozoraDev** [comment]
@fred913 
I don't think so.
Just use rate limit to refuse the request from that bad person.
Also, you can make the API detect same counts or same click interval, so that you can block the IP Address from using the API.

**Comment by fred913** [comment]
@AozoraDev I apologize for confusing things I've made, but what I actually referred to is changing to WebSocket, earlier.

**Comment by fred913** [comment]
Since the issue does not present in recent versions since they don't use any online services, it'll be closed temporily.

**Comment by sr229** [comment]
This is a little late, but I kind of have a solution on hand, which involves SSEs and event streams. It's technically impossible to spam the API since nothing is exposed to the client and requires an actual BroadcastChannel to even interact to.

[Here's my PoC, which is kind of incomplete](https://github.com/sr229/kuru-kuru).
