### ISSUE TITLE
About Copyright and Licences

### ISSUE THREAD

**Issue by KawaiiShadowii** [duiqt/herta_kuru#44]
Hello,

I am the sole developer of [tannhauser.moe](https://tannhauser.moe/).

I have come across your website and it has come to my attention that there are quite a few similarities between your and my website including HTML structure, CSS styles and JS functions to the point where a lot of the website has been taken 1:1 from [tannhauser.moe](https://tannhauser.moe/).

I think it's safe to assume that you took my project without permission and changed some things to make your own website.

To be clear, I don't mind you doing this, but I do not agree with you not crediting me or the original website anywhere. Also, please remove the license from your project which claims that you are the copyright holder of this project as the copyright to the HTML, CSS and parts of JS belong to me.

I want to reiterate that I do not initially plan on taking this project down, but I ask you to credit [tannhauser.moe](https://tannhauser.moe/) and myself on your website and in the repository, please.

Kind Regards
![image](https://github.com/duiqt/herta_kuru/assets/33539431/e5d890e5-175e-4463-b5a5-d9b23d5ef455)
![image](https://github.com/duiqt/herta_kuru/assets/33539431/e5ed3d20-8d34-4355-a98e-83fa0d3f2e35)
![image](https://github.com/duiqt/herta_kuru/assets/33539431/d065f13b-e761-4585-b716-9a11f9ce86ba)
![image](https://github.com/duiqt/herta_kuru/assets/33539431/f6c15c29-4ffa-4c09-b6c9-aa12959b0e3f)
![image](https://github.com/duiqt/herta_kuru/assets/33539431/fe893927-7130-4435-98bf-9684c59f6f6e)
![image](https://github.com/duiqt/herta_kuru/assets/33539431/9d7d93e6-66a2-4683-abd7-60c4db2f9c7b)
![image](https://github.com/duiqt/herta_kuru/assets/33539431/dd77775f-0d85-49a1-9c44-85e877c70ea6)

**Comment by fred913** [comment]
Dear KawaiiShadowii,

Thank you for reaching out to me. I want to sincerely apologize for the similarities between our websites and for not seeking permission or providing proper credit.

I understand your concerns regarding the lack of attribution and the unauthorized use of your code. I genuinely appreciate your willingness to allow me to keep the project online, and I understand the importance of giving credit where it is due.

I assure you that I will take immediate action to address the situation. I will rewrite all code sections that resemble tannhauser.moe to ensure they are original and distinct. However, I must kindly request that I cannot shut down our website completely due to the high traffic it receives.

Nevertheless, I want to emphasize that I will make the necessary changes to respect your ownership and copyright. I will amend the license to reflect the appropriate information and prominently credit tannhauser.moe and yourself as the original source of inspiration for my website.

I apologize for any inconvenience caused, and I assure you that this was not done with malicious intent. Thank you for understanding and bringing this matter to my attention. If there are any other specific details or requirements you would like me to consider, please let me know, and I will do my best to accommodate them.

Best regards,
Sheng Fan

**Comment by fred913** [comment]
'll reply soon, as soon as I finish the huge change of the code. Once I have completed these changes, I would be delighted to invite you to review it and provide your feedback.

**Comment by fred913** [comment]
@KawaiiShadowii I have finished working on the credits dialog, but I'm not sure if the current sorting method is appropriate. If you have any concerns, please don't hesitate to ask me to make adjustments.

**Comment by KawaiiShadowii** [comment]
@fred913 Thank you for putting me in the credits and for putting tannhauser.moe in the readme. It is very much appreciated.
You don't have to, but I'd appreciate it if there was a link to tannhauser.moe somewhere on the website as well, but if you don't want to then that's okay. I think the sorting of the credits doesn't matter too much, so you can go ahead and do it however you like. Thank you very much for your cooperation and I hope you website will continue to do well.

**Comment by fred913** [comment]
That's because the implementation of credits dialog hasn't finished yet.
After an inspection of the credits.json you'll see that everyone has social
media information, which isn't used by the frontend controllers. That's
what we're going to implement in future versions.

**Comment by fred913** [comment]
Now it's completed.
